### ISSUE TITLE
[data-grid] new data type

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#103]
Hi @yurikuzn , in some cases my customer needed a basic data grid data type to be added to some entity.
It is some thing like saving the data in just a one text column as a JSON, and I may start performing it, but I found to ask you before, are you interested in this new type to be pulled to the repository, if yes I will take your standards in consideration, and hear your instructions.

**Comment by yurikuzn** [comment]
Hi

Not sure. If you will develop it on GitHub you can look when you make it.

**Comment by ayman-alkom** [comment]
Hi @yurikuzn 
I have made a small plugin representing the DataGrid data type, I liked to share you the link to make a look when you have a time.

You may add it to the Espo core

**Comment by ayman-alkom** [comment]
https://github.com/ayman-alkom/EspoDataGrid

**Comment by yurikuzn** [comment]
Looks good.

A few notes:
* Better to use `{{./this}}` instead of `{{this}}` in templates. It concerns only `this` variable.
* "Add Item" label available only in Advanced Pack.
* `kobit:admin/field-manager/fields/data-grid-columns` instead of Kobit:admin/field-manager/fields/data-grid-columns.
* `kobit:views/fields/data-grid` instead of "Kobit:fields.data-grid".

**Comment by ayman-alkom** [comment]
thanks a lot for your instant notes. I will follow there
