### ISSUE TITLE
Company years

### ISSUE THREAD

**Issue by OlofBailey** [espocrm/espocrm#1063]
At least 50% of companies don’t follow calendar years.
I think the company year as used for reporting needs to be an easy and upgrade safe change either in the backend or a config file.

**Comment by richbailey** [comment]
Hi

Our financial year is June to May rather than Jan to December. I’m sure this is the same for lots of companies, certainly in the UK using calendar years for company reporting is rare.

We need to be able to set the first month of the year and then all filters and reporting needs to follow this, e.g. filters for quarters and years.

**Comment by OlofBailey** [comment]
Does this make sense? Any chance of this making it in?

**Comment by yurikuzn** [comment]
It makes sense. Not sure whether we will do it soon. Very lot of things in our todo list.

**Comment by OlofBailey** [comment]
Great, I’m sure this affects a lot of users. At least 80% of uk customers won’t use calendar year. 
50% are probably tax year and the rest an arbitrary month based on formation.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1100

**Comment by bandtank** [comment]
@OlofBailey I can't help but laugh at how extreme your comments are. The advanced pack, even four years ago, was more than capable of handling variations in year start and end dates.
