### ISSUE TITLE
Administrative menus in the main menu?

### ISSUE THREAD

**Issue by pomazanbohdan** [espocrm/espocrm#1180]
It would be nice to be able to add some items from the administrative menu to the menu.

As an option, the ability to add custom URL "/ portal"

**Comment by Hofundur** [comment]
It could be nice to add Custom Links into menu. Now, for example, if i wanna show portal users in view that is available from main menu, i changed /#User views.

It may be usefull for external resources like git, counfluence etc to link for users in one system.

**Comment by mstaack** [comment]
@logicplus have you uploaded your code somewhere?

**Comment by tonybyng** [comment]
I'd be interested in using this - unfortunately i'm new to espo and hoping to find a tutorial somewhere on how to do things like this. At the moment, i have simply created an entity called "useful links", put a wysiwyg element in the entity and created a dashboard widget which lists the contents in order, so that i have easy links to accounts system, github etc. but it would be great to be able to have a side menu called "external links"
