### ISSUE TITLE
Email Reply-to All should not include the email we are replying from

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#1275]
# Problem

Imaging my group email is karthik@gmail.com. Someone sent me an email from say test@gmail.com. When I click reply-to-all from a case/anywhere else, 
currently:
- the from address: karthik@gmail.com
- the to address: test@gmail.com
- cc to address: karthik@gmail.com

Expected:
- the from address: karthik@gmail.com
- the to address: test@gmail.com
no cc.

Take gmail's application for example and see how it works.

**Comment by yurikuzn** [comment]
I assume this happens if karthik@gmail.com is not a users primary email address and user selects this address in the From select box when replying on an email.

This is a tricky issue, as when replying on an email it assumes that it will be replied from the user's primary email hence  pre-fills the CC with the the email address the original email was sent to. Not sure what we could do.
