### ISSUE TITLE
Lead Capture: Field with Enum returns 500: Internal Server Error

### ISSUE THREAD

**Issue by tvld** [espocrm/espocrm#1308]
Given a new Lead field created with EntityManger in Espo 5.6.1 : ``mycode | MyCode | Multi-Enum``
When sending with Postman or node/axios:
```json
{
    "firstName": "John",
    "lastName": "Test",
    "emailAddress": "john9@test.com",
    "mycode": "[\"one\",\"two\"]"
}
```
Server responds with `` 500: Internal Server Error`` although the record is created correctly and the ``mycode`` field will get the correct ``one,two`` values.

Expected: return the normal ``200, ok`` as there seems no error.

**Comment by vlasix** [comment]
I tested this exact sample with 5.6.3 and works fine. Can you post server (apache, nginx) logs and your htdocs/data/logs/espo-yyyy-mm-dd.log?

**Comment by tvld** [comment]
Posting:
```
{
    "firstName": "John",
    "lastName": "Test",
    "emailAddress": "john@test.com",
    "qcode": "[\"one\",\"two\"]"
}
```

Nginx:
```
192.168.1.1 - - [11/May/2019:15:29:15 +0200] "POST /api/v1/LeadCapture/1234567890xxxxxxxxxxxx HTTP/1.1" 200 35 "-" "PostmanRuntime/7.6.0"
```

```
[2019-05-11 13:27:10] Espo.ERROR: API [POST]:/LeadCapture/:apiKey, Params:Array (     [apiKey] => 1234567890xxxxxxxxxxxx ) , InputData: {     "firstName": "John",     "lastName": "Test",     "emailAddress": "john@test.com",     "qcode": "[\"one\",\"two\"]" } - ArrayValue: Bad value passed to JSON_ARRAY attribute qcode. [] []
[2019-05-11 13:27:10] Espo.ERROR: Display Error: ArrayValue: Bad value passed to JSON_ARRAY attribute qcode., Code: 500 URL: /api/v1/LeadCapture/3ad57ae606015c6cdd73b84fd6445be1 [] []

```

**Comment by tvld** [comment]
And if I post:
```
{
    "firstName": "John",
    "lastName": "Test",
    "emailAddress": "john@test.com",
    "qcode": "\"one\",\"two\""
}
```
Reponse is same:
```
[2019-05-11 13:35:40] Espo.ERROR: API [POST]:/LeadCapture/:apiKey, Params:Array (     [apiKey] => 1234567890xxxxxxxxxxxx ) , InputData: {     "firstName": "John",     "lastName": "Test",     "emailAddress": "john@test.com",     "qcode": "\"one\",\"two\"" } - ArrayValue: Bad value passed to JSON_ARRAY attribute qcode. [] []
[2019-05-11 13:35:40] Espo.ERROR: Display Error: ArrayValue: Bad value passed to JSON_ARRAY attribute qcode., Code: 500 URL: /api/v1/LeadCapture/1234567890xxxxxxxxxxxx [] []

```

**Comment by tvld** [comment]
Please note that the error is _only_ coming the _first call_, so when the record is created. If the record (email) already exists, we get a ``200, OK``

**Comment by vlasix** [comment]
Hi Tom, I found the error. You're passing the array as a string. Use this:
{
    "firstName": "Bilbo",
    "lastName": "Baggins",
    "emailAddress": "bilbo.baggins@shire.me",
    "mycode": ["one","two"]
}

**Comment by tvld** [comment]
Oops... :)).... Thank you. I sent the field as JSON.stringify ... but I should have sent indeed just an array ... Thanks again

**Comment by corinamarkodimitraki** [comment]
Could not add line 2 of this table due to error 500 upon saving the commune. We will need to look into this in the next sprint. 

<a class="CID72a22449-119e-4c2a-aae3-410523a7b7ae" data-sessionid="77daf9c4-4d2f-8087-143c-0752373e13e6" data-shapeids="4" data-slideid=""> </a><div>
N°​ | Date​ | Regions​ | Localités​ | Lieux​ | Natures​ | Personnes sinistrées​ | Hommes​ | Femmes​ | Enfants​ | Blessés​ | pertes en vies humaines​ | Impacts​
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1​ | 02/09/2024​ | Douantzan ​ | Cercle de douantzan ​ | douantzan ville​ | Inondation​ | 823​ | 275​ | 548​ | 0​ | 0​ | 0​ | 175 ménages Touchées, ​178 Murs tombés, ​26 greniers détruits, ​16 Magasins, ​63 Toilettes tombées, ​50 champs de cultures, ​08 jardin de cultures détruits, ​18 caprin, ​194 volailles, ​10 puits endommages​
2​ | 02/09/2024​ | Douantzan ​ | Commune rulale de petaka​ | Gonou​ | Inondation​ | 384​ | 128​ | 100​ | 156​ | 0​ | 0​ | 64 ménages Touches, ​64 Maison Tombées​25 grenier détruits,​ 25 Bovin emporter,​30 caprin, ​50 volailles emporter, ​2 motos emporter, ​05 charrettes emportées,​03 écoles détruites,​01 mosquée détruite​
3​ | 02/09/2024​ | Douantzan ​ | Cercle de douantzan ​ | Cercle de Fombory​ | Inondation​ | 421​ | 51​ | 68​ | 302​ | 0​ | 0​ | 49 ménages toucher, ​08 Maison effondrées,​19 latrine, ​bovin ovin emporter 03,​grenier détruits 10,​15 champs de cultures détruits,​ 2550kg de céréales détruite​
4​ | 02/09/2024​ | Douantzan ​ | Cercle de douantzan ​ | douantzan ville​ | Inondation​ | 128​ | 15​ | 21​ | 92​ | 0​ | 0​ | 17 ménages touches ​04 Maison effondre, ​09 latrines,​03 greniers,​

</div>
