### ISSUE TITLE
Feature request: A better Wysiwyg editor. 

### ISSUE THREAD

**Issue by hdijkema** [espocrm/espocrm#1801]
The current editor is very limited compared to some good open source wysiwyg HTML editors available.

It is hard without the <> to get e.g. a good formatted table. And also more formatting tags are created then is necessary and they are not always good for the markup.

E.g.: https://github.com/tinymce/tinymce

Or is it already possible to replace 'summernote' with something else?

**Comment by yurikuzn** [comment]
It's quite a lot of work to replace. We have some customization done for summernote.

**Comment by hdijkema** [comment]
Can you elaborate a littlebit on the customization?

**Comment by yurikuzn** [comment]
Dialogs are customized to fit espocrm UI design: https://github.com/espocrm/espocrm/blob/master/client/src/views/fields/wysiwyg.js

**Comment by M0hamedSalem** [comment]
Are there any plans or intentions for this update soon?

**Comment by radek3911** [comment]
Hello, if you are interested let me know. We have implemented a CK Editor 5 as Espo customization.

If advertising is allowed here feel free to contact me at info@autocrm.cz (if it is not please remove this comment)
![image](https://github.com/espocrm/espocrm/assets/15276167/a92db702-9bda-4f68-ac27-d4d4ba693a34)
![image](https://github.com/espocrm/espocrm/assets/15276167/89b021e1-5a2b-48d6-954c-a368890e5aa8)

**Comment by yurikuzn** [comment]
Under the hood the editors are all the same contenteditable, there should not be any drastic difference with markup they produce. It's very unlikely that we change the editor any soon, instead we could improve the current one. But to be able to improve, we need to know what exactly issues are present, how to reproduce them and what exactly vital features are missing.

**Comment by radek3911** [comment]
> Under the hood the editors are all the same contenteditable, there should not be any drastic difference with markup they produce. It's very unlikely that we change the editor any soon, instead we could improve the current one. But to be able to improve, we need to know what exactly issues are present, how to reproduce them and what exactly vital features are missing.

The CK editor we implemented was on-demand by client, because they wanted to make a nice knowledge base and needed the extra features of CK editor (better tables, font options etc.)

The summer note is not itself bad, but quite limited and the biggest flaw(feature) is formatting. We also had to implement Ace editor in combination with puppeteer PDF engine, because we weren't able to make good PDF templates, any custom styles got stripped by summernote and the only option was to fill the HTML in DB (until we implemented the ace editor) - I am not sure if "clean text" was an option at the time we implemented Ace.

But I can see that you are reworking this in 8.2.0 so probably the ace editor will be a built in option?

**Comment by yurikuzn** [comment]
Could you provide an example of custom styles being stripped. If it strips, does any other Wysiwig not strip it? I assume any editor based on contenteditable will style tags.

**Comment by radek3911** [comment]
> Could you provide an example of custom styles being stripped. If it strips, does any other Wysiwig not strip it? I assume any editor based on contenteditable will strip style tags.

We had a problem mostly around PDF templates where we wanted to (for example) make a full HTML page (with <head> <body> <style> tags etc.). This was impossible in the summer note (or so I recall) so we implemented ace editor to edit HTML directly with syntax highlighting. It was around version 7.3 (and the clear text template option was also our customization so sorry for the misunderstanding), so when we wanted a complex template (usually invoice with complex layout and styling) we ran into issue where the styles and layout would get purged if we inserted it as code in the summernote. Which is of course intended behavior (for any other parts of the CRM - not to allow HTML because that is XSS) but for the goal of having complex PDF templates it was a "flaw". 

Alongside ace editor we did implement the puppeteer PDF engine which worked great in comparison to Dom PDF. While using Dom PDF we also ran into other issues with the HTML rendering.

I just checked 8.2.0 demo, and I am not sure if we would still need to use ace editor for the template body, I tested it out with one of the template we are working on and when seperating the style and body into the wysiwig and style field the template completely broke (altough I beleive that was more likely caused by dompdf rather than wysiwig stripping it - need more time to test it)

> Yes. Plus it's possible to specify styles (CSS) separately for PDF templates (only).

This is nice, I just tried it out and it seems to be working on demo.espocrm.com, however the template still turned "crooked" after printing (I am very positive that it's due to Dompdf through)

> What exactly is wrong with formatting? How other editors perform better here?

The flaw I was referring to is stripping the custom styles, otherwise I don't see any issue (not exactly an issue for typical end-user)

> What is meant by font options? Different fonts? I don't think we can support different fonts for both PDF and frontend. Anyway having different fonts on the same page is not good from the UI design point of view.

Yes, switching fonts as the client had a company wide font "branding rules", now that I think of it, we probably should have handled it differently - using just custom css for the entire espo crm instance. I don't exactly recall, why they wanted a different editor, but looking at the usage it seems to me that the table functions of CK editor (+ the fonts) and probably the more "intuitive UX" were the main points. CK editor has a lot more features for making tables in wysiwig and also a lot more plugins that can get added on demand.

I will test a bit more with PDF templates in 8.2.0 and get back to you, thank you for all your hard work.

**Comment by yurikuzn** [comment]
> stripping the custom styles, 

Actually, we strip style tags on purpose, to prevent the page layout and style being affected by the field. It's not the editor.

**Comment by stepstep7** [comment]
I really dislike the fact you can't strip ALL formatting from text with current WYSIWYG editor. There is a button that's supposed to remove the styling, but it just doesn't cut it. 
I don't want every line to be included in <p> tags, it makes text bloated with these empty <p></p> lines, and also that button can't deal with nested embedded style tags.  All i wish is to paste whatever, and then get a simple, plain, <div> kind of text after removing the formatting.  Selecting "Normal" style doesn't do it.

Also working with images is problematic:  for example you can't just click on it and center on page -- you have to "select it" like a long line of text to make it blue, and only then it will agree to be centered. Can't delete images either: you must find the huge blinking line on the left side of image, and only then press Del - any other way of deleting doesn't seem to work.

I also couldn't Ctrl+A the entire page and change properties of all text -- it only does it for the first paragraph after cursor, or something like that.

**Comment by yurikuzn** [comment]
Ctrl + Shift + V – paste plain text
Shift + Enter – add line break without paragraph

These hotkeys are not specific only to the Summernote editor.

**Comment by stepstep7** [comment]
> Ctrl + Shift + V – paste plain text Shift + Enter – add line break without paragraph

yea i know, but it simply doesn't work. to test it i created a plain text in notepad:
```
1
2
3
4
```
I then go to espo, create new article, go to empty wysiwyg field, Press `Ctrl+Shift+V`, and it still does this:
`<p>1</p><p>2</p><p>3</p><p>4</p>`

P. S. not trying to be demanding or anything, you guys are doing wonderful job, and i really like this CRM -- Thank you for it.

Just a little riled up cause I pasted a text from doc file to Knowledge Base Article, and editing it was absolute hell, as the Remove Font Style button doesn't seem to fully remove formatting. in the end i just gave up and ended up editing the soruce, manually removing the tags.

**Comment by bandtank** [comment]
I have issues with this sometimes as well, but it generally works if you paste plain text and then format the content. It isn't perfect, but it works well 99% of the time. Interestingly, pasting the example text you showed above also inserted paragraph tags for me, which I don't think happened in version 5, which is the last time I needed to do that. A lot has changed since then, so who knows what could be causing it. I like the idea of a better WYSIWIG editor, but it doesn't seem to be a major roadblock for most situations.
