### ISSUE TITLE
Security issue - user can read other users email

### ISSUE THREAD

**Issue by david-strejc** [espocrm/espocrm#1849]
When I setup my own user account in a way that I will write an email address of my boss to my email address, I can see his emails from that time on.

This is real big security risk.

**Comment by yurikuzn** [comment]
Please describe issue more detail. It's not clear.

**Comment by yurikuzn** [comment]
User can see all emails if their email address is in FROM, TO, OR CC.

**Comment by jarca0123** [comment]
He meant if you give User A the permission to edit their own fields in the User entity, then the email field can also be edited, and when User A assigns themselves the email of User B (provided that the email address of User B has its EmailAccount), then any future emails will be sent to User B and User A, despite the fact that User A doesn't have access to the EmailAccount of User B.

This could be fixed by putting this in application/Espo/Repositories/User.php on line 127:
```
if ($this->getEntityManager()->getLocker()->isLocked()) {
            $this->getEntityManager()->getLocker()->commit();
}

if ($entity->isNew()) {
    $emailAddress = $entity->get('emailAddress');
    if (empty($emailAddress)) {
        return;
    }

    $user = $this
        ->select(['id'])
        ->where([
            'emailAddress' => $emailAddress,
        ])
        ->findOne();

    if ($user) {
        throw new Conflict(json_encode(['reason' => 'emailExists']));
    }
} else {
    if ($entity->isAttributeChanged('emailAddress')) {
        $emailAddress = $entity->get('emailAddress');
        if (empty($emailAddress)) {
            return;
        }

        $user = $this
            ->select(['id'])
            ->where([
                'emailAddress' => $emailAddress,
                'id!=' => $entity->id,
            ])
            ->findOne();

        if ($user) {
            throw new Conflict(json_encode(['reason' => 'emailExists']));
        }
    }
}
```

**Comment by yurikuzn** [comment]
It's better to forbid 'edit' access to *Email* field via Roles. I though that it's forbidden by default. I think we have to make it read-only for non-admin users.

**Comment by yurikuzn** [comment]
The fix you provided is not enough, because one can change their email to for example an email address of some account. 

When I designed access control logic I did not suppose that it will be possible to make email field editable for users in future. I think we need to remove the ability to edit email field for all non-admin users as it was intended to be initially.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1851
