### ISSUE TITLE
Saturday is weekStart in some countries

### ISSUE THREAD

**Issue by mohammad6006** [espocrm/espocrm#1893]
Saturday is weekStart in some countries but there is no option to select Saturday in installer on config

**Comment by bandtank** [comment]
Sunday is the beginning of my week in terms of social norms, but Wednesday would make more sense for my business. I think every day of the week should be an option.

**Comment by o-data** [comment]
All it does it move what is the most lefthand side on /#calendars isn't it? I don't think it affect anything else?

**Comment by yurikuzn** [comment]
You can try to add missing numbers here: https://github.com/espocrm/espocrm/blob/6.1.0/application/Espo/Resources/metadata/entityDefs/Settings.json#L41
Better to do it in the custom folder though. If someone try this please let me know how it works.

**Comment by bandtank** [comment]
I’m having trouble responding to your comment without being condescending because your perspective is narrow minded and somewhat arrogant.

In short, people all over the world use things differently and it is never as simple as “all it does is...”. When I look at a calendar that doesn’t start on Sunday, it confuses the hell out of me for a few seconds. I know others feel the same way when they’re expecting a week that starts on Monday in the opposite situation. Whether or not the change is implemented is different than whether or not it makes sense for the users. It’s a pretty easy thing to change and there are options for number and time formats, so maybe Yuri will add the other days. If you don’t want to use it, then don’t.

**Comment by yurikuzn** [comment]
The comment you replied must have been deleted.

It will save us time if someone will try the fix I proposed on their production instance and report if any issues occur.

**Comment by o-data** [comment]
@bandtank Hi Bandtank, not sure if you are referring to me but I assume it is since you quote "all it does"; I don't mean that in a bad way and you believe might have misread me. What I'm trying to say it "All it does is move to the left hand side, so making that modification you propose shouldn't anything else". Mean it might work, but who knows whether it does or not.

Whatever I write will never mean hostility, I do many "short-cut" or "work around method" and will usually suggest that as a solution, join to the forums and you might be surprise the amount of information there.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/1953
