### ISSUE TITLE
LDAP error when user is created

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#1935]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/2ae0f362417ffed85280921e2b42e66b77bc6075

**Comment by gramakri** [comment]
@yurikuzn It seems that after this change when a new LDAP user logs in they see an error "500: User must be fetched before ACL check" from https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Acl/Table.php#L118 . If the user attempts to login a second time, it works fine.

Login was fine with 6.1.4.

**Comment by tmachyshyn** [comment]
@gramakri 

I cannot reproduce the bug. Test environment: EspoCRM 6.1.5 and OpenLDAP server.
Could you let me know what LDAP server do you use?

**Comment by gramakri** [comment]
@tmachyshyn sorry for the delay. This was a false alarm, it looks like.

**Comment by gramakri** [comment]
@tmachyshyn I can actually reproduce this quite reliably. The LDAP sever is Cloudron LDAP.

I wonder if this is a bug or a feature. Can you first tell me if the LDAP user has to be synced into EspoCRM for the login to work? [related](https://github.com/espocrm/espocrm/issues/1244)

**Comment by tmachyshyn** [comment]
For the first login, EspoCRM loads data from LDAP server and creates a user.
For the next logins, EspoCRM just check authorization pass from LDAP server.

Could you describe steps to reproduce this bug.

**Comment by nebulade** [comment]
To add a bit more context what is happening, since this seems related, the very first login attempt fails. Immediately after that resubmitting the login form succeeds fine. So looks like after the first attempt it syncs the user from LDAP fine and thus then allows to login. As @gramakri mentions, not sure if this just expected or a bug.

**Comment by tmachyshyn** [comment]
Ok. I will check this for Cloudron LDAP.

**Comment by gramakri** [comment]
@tmachyshyn I don't think it's specific to Cloudron LDAP. Just LDAP in general. I think what we want to know is if this is the expected behavior - that the first LDAP login of a new user will fail (unless a sync is done before hand).

**Comment by tmachyshyn** [comment]
@nebulade our team installed the Clouddron on our local server. It looks very good. Thanks for the hard work.
It seems we found a few issues:
1. The internal EspoCRM log is not storing due to a broken link in `/home/yellowtent/appsdata/<APP_ID>/data/data/logs`. The target directory is `/run/espocrm/logs` which is doesn't exist.
2. The same thing is with `cache` directory.

Could you describe how user authentication works? As I understand:
1. After EspoCRM installation, the authentication method is set to LDAP and linked with your external Cloudron LDAP server?
2. What happens when a new user (regular user) is created via EspoCRM administrator panel? In my case, I cannot login under a new user.
Thanks

**Comment by nebulade** [comment]
sorry for the late reply. Regarding the missing symlinks, I think there is a misunderstanding how this works on Cloudron. The folder `/home/yellowtent/appsdata/<APP_ID>/data` will be mounted as `/app/data` within the app container. Also the app container will get its own `/run/` which I can see within the container the symlinks are valid and the logs are stored correctly.

This still leaves us with the LDAP login issue. I looked into the log file now that I was aware where it is ;-)
So what I did was to login first with the pre-setup admin account (not LDAP) and that worked. Then after a logout, I submitted the login form once for an LDAP user. This failed. However submitting the form again right-away then also made it succeed.
The logs thus are as follows:
```
src/StreamSelectLoop.php","line":226} []
[2021-05-06 11:01:55] ERROR: LDAP: Authentication failed for user [admin], details: user is not found. [] []
[2021-05-06 11:01:56] WARNING: E_WARNING: pcntl_signal_dispatch() has been disabled for security reasons {"code":2,"message":"pcntl_signal_dispatch() has been disabled for security reasons","file":"/app/code/6.1.7/vendor/react/event-loop/src/StreamSelectLoop.php","line":226} []
...
[2021-05-06 11:02:03] ERROR: (500) User must be fetched before ACL check.; GET /App/user; line: 119, file: /app/code/6.1.7/application/Espo/Core/Acl/Table.php [] []
[2021-05-06 12:07:02] WARNING: E_WARNING: pcntl_signal_dispatch() has been disabled for security reasons {"code":2,"message":"pcntl_signal_dispatch() has been disabled for security reasons","file":"/app/code/6.1.7/vendor/react/event-loop/src/StreamSelectLoop.php","line":226} []
```

The `...` just show a lot more of those WARNINGs. But I don't think they are related.
Does this give any further clue? Or is there anything I could set to get more relevant logs here?
