### ISSUE TITLE
Import stop when wrong email format

### ISSUE THREAD

**Issue by eymen-elkum** [espocrm/espocrm#2133]
**Describe the bug**
When I import csv to contacts stopped at wrong email format

**To Reproduce**
1. any csv file with wrong email value like this: bla.bla.@example.com
2. run import as normal

**Expected behavior**
I expected it to skip the wrong field or the whole record, but it stopped and marked as completed without continuing further contacts.

**EspoCRM version**
7.0.7

**Comment by yurikuzn** [comment]
This is difficult to fix. Needs revising the current logic. If we skip all bad rows, we will need log errors somehow. If we had every row invalid (producing an error) we would possibly have thousands of records in the log. That is not good. I opt to stick to the current logic for now with the difference that the status will be set to Failed, and a bad email address will be printed in the log so that user would be able to fix and continue the import.

https://github.com/espocrm/espocrm/commit/33e1f4871749e4bf98c14374b5c09f911b8c690c

**Comment by eymen-elkum** [comment]
Actually I fixed it but not sure if that was the best practice , I only surrounded [this line](https://github.com/espocrm/espocrm/blob/master/application/Espo/Tools/Import/Import.php#L331) with try catch:

```
try {
     $rowResult = $this->importRow($attributeList, $row);
} catch (Exception $exception) {
     $rowResult = null;
}

```

**Comment by yurikuzn** [comment]
I tried to explain why I didn't want to do it in my previous comment.

**Comment by eymen-elkum** [comment]
I see,
Just an idea, maybe we can store those un-success records on some place and only show them on the import result as an additional pane, just like the duplicated panel.

For example we may define a new table linked to import with jsonObject field

**Comment by yurikuzn** [comment]
Yes, but this requires some effort and can't be a subject of a hotfix release.
