### ISSUE TITLE
Mass Email: Supporting custom entity types as recipients

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2203]
The admin needs to create a Many-to-Many relationship between the Target List and a custom entity (of Person or Company type). Then add the panel to the Bottom Panels layout of the Target List entity.

**Comment by jlcastillo** [comment]
Thanks @yurikuzn, I added the Many-to-Many relationship between TargetList and my custom entity, and added the custom entity to the bottom panel layout of TargetList. I'm now able to add custom entity items to the target list. However I'm not able to sync with Mailchimp. The MailChimp API key is working properly because I'm successfully populating the Mailchimp Contacts groups in EspoCrm. But EspoCrm doesn't see to be syncronizing the target list.

From all your instructions, the one I didn't do was "add the link name in metadata by the path: scopes > TargetList > targetLinkList:", because I don't find the file where I should add this snippet.

Did you already add this feature to the documentation? I didn't find it either.
