### ISSUE TITLE
Ability to collapse Compose Email modal

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2222]
To be able to continue composing the email later. For example, when some text needs to be copied, a user can collapse the modal window, copy the text and then resume composing.

Upon collapsing the email is saved to draft. So that if the window is closed, the composed email won't be lost.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/9408a1637d21c18c7bee06d51d4a9a11d61f5848

**Comment by rabiibrahimi** [comment]
Hi @yurikuzn , 

This works fine however is it possible to improve the UI. i suggest that the email is collapsed it should be set at bottom right of the screen and also it the bar could have more margin top so that it appears properly when it is collapsed. see attached screen shot how it looks now. (it is not properly set on the bottom right of the screen and it is too small to be noticed)

Great work 
Thanks again
<img width="1237" alt="Screenshot 2022-03-21 at 18 17 53" src="https://user-images.githubusercontent.com/19490674/159328814-74de4919-b8df-4bcf-987d-1c62158d5bed.png">

**Comment by yurikuzn** [comment]
The idea of positioning if taken from Gmail.

Regarding the top margin, I don't understand. It looks OK to me in my browser.

**Comment by rabiibrahimi** [comment]
@yurikuzn I understand i have checked the gmail and it seems that on gmail it is almost positioned at the bottom right. What i meant by the margin top and bottom (is the height of the div). see attached screen shot from gmail. 

Again many thanks 

<img width="1278" alt="Screenshot 2022-03-21 at 19 37 33" src="https://user-images.githubusercontent.com/19490674/159341959-88827ef2-8e4d-45ad-9949-38999472f0aa.png">

**Comment by yurikuzn** [comment]
I think that making it taller will cause overlapping with content in some cases (even if scrolled to the bottom). That's what it is of that hight.

**Comment by yurikuzn** [comment]
Moved 200 px to the right: https://github.com/espocrm/espocrm/commit/51a6b304f2fb7e71f8474a5b299bb141433f7528

**Comment by rabiibrahimi** [comment]
Thanks @yurikuzn  🙏
