### ISSUE TITLE
Ability to click URLs in Array

### ISSUE THREAD

**Issue by switchupcb** [espocrm/espocrm#2239]
**Is your feature request related to a problem? Please describe.**
The ability to add multiple click-able URLs to a field without using a link-multiple.

**Describe the solution you'd like**
The ability to click http and https URL's in an array, or a "URL-multiple" type field.

**Describe alternatives you've considered**
https://docs.espocrm.com/administration/fields/#link-multiple

**Additional context**
There may be a way to do this already that I'm unaware of.

**Comment by switchupcb** [comment]
Be sure to prioritize your safety and health.

**Comment by bandtank** [comment]
Using an RTF field is overkill.

In addition to this request, it would be great if URL fields could use a key -> value system. It's unwieldy to have long URLs in Link fields.

In other words, if I could put a link in the `Resources` field called `Client Documents` instead of a literal URL, it would look much cleaner.

![Screen Shot 2022-04-06 at 9 59 27 AM](https://user-images.githubusercontent.com/1170415/162017648-733c3aa5-dcfe-45ae-ad1f-e62e8566d47c.png)
w

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/issues/2713
