### ISSUE TITLE
Detail view tabs

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2379]
Available for *Detail* and *Detail (Small)* layouts.

![tabs](https://user-images.githubusercontent.com/1006792/179352355-58ca136c-03cd-4a16-9b25-5169f5a61700.png)

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/518fe07ea1f23a997cb524267918a197d32c4f35

**Comment by rabiibrahimi** [comment]
could the tabs also be activated for relationship panels (grouped as tabs). will still support previous panels functionalities like hidden panels, coloured panels etc ? 

This is a great features it will definitely improve the user experience. 

Many thanks for your great work, can't wait to use it.

**Comment by yurikuzn** [comment]
Maybe in future. Please, don't ask me to add new features. I've been working too much.

> functionalities like hidden panels, conditionally hiding panels, coloured panels etc ?

Please, you can build and test and let us know. Hidden panels with show more button is not fully supported with tabs.

**Comment by rabiibrahimi** [comment]
I see many thanks. 

currently we use certain panels on accounts (show them) only when type of account is customer and we hide them if type of account is investor, such dynamic logic will still work with tabs ? e.g show / hide certain tabs based on a condition defined for each tab (same as it was used for panels) i think such  conditional hiding/showing of tabs will be very useful.

i will build and test it out and let you know if there are any issues. 

many thanks for your effort and great work we really appreciate it so much

**Comment by yurikuzn** [comment]
* Tabs are being hidden/shown with their panels being hidden/shown. Except for the first tab, it's always shown.
* Panel colors has nothing to do with tabs functionality.

I committed some changes. Make sure you have a fresh pull.

**Comment by rabiibrahimi** [comment]
Hi i have been playing around with tabs and it seems a great addition, however when using condition to hide / show certain panels the system would only hide the panel but not the tab related to that panel. e.g i have a account with 4 tabs (overview/details/customer info/partner info) i have conditionally put logic for customer info panel to be shown only when type of the account equals Customer and same for Partner Info panel it should be hidden unless the account type equals Partner, it seems that the logic applies only to panels and not tabs which means when account type equals Customer then panel and tab are shown (Customer Info) but Tab Partner Info should be hidden hence it doesn't meet the condition to be visible which type equals Partner, seems that only panel will be hidden but not the tab related to that panel. also in terms of design the first two tabs seems to not have a bottom border but the last two tabs have a panel bottom border. hope this is clear for you. see attached screenshots.
<img width="1470" alt="Screenshot 2022-07-17 at 13 14 20" src="https://user-images.githubusercontent.com/19490674/179398173-d5e9f05e-4d90-466b-b2e7-3ad5bd5f5685.png">
<img width="1470" alt="Screenshot 2022-07-17 at 13 16 23" src="https://user-images.githubusercontent.com/19490674/179398178-8a3571b5-bef4-414f-8b5c-daecd9ca0dd7.png">
<img width="1470" alt="Screenshot 2022-07-17 at 13 23 20" src="https://user-images.githubusercontent.com/19490674/179398182-fb105f8d-42bb-4e93-8dbd-5917afff8f7d.png">
<img width="1470" alt="Screenshot 2022-07-17 at 13 24 03" src="https://user-images.githubusercontent.com/19490674/179398185-0aa9f35e-18c9-431e-9e0c-e68d284a996f.png">

**Comment by yurikuzn** [comment]
Did you test with the latest commits?

**Comment by rabiibrahimi** [comment]
I have tested the functionalities of tabs with the latest commit and it is fantastic. now supports hidden tabs based on conditions, also i loved how you handled validation for required field on tab level, however when a hidden tab has a required field and when trying to edit the record the validation message is shown, i think a workaround is to use condition on field level when it should become required and that would solved such issue, since there is no way to fix with the design. see attached screenshot for validation. Other then that i think this tabs feature is very reach and very useful and it is fully functioning without any issues, i have run a lot of test against each functionality and all it working without issues. In terms of the Border bottom they are fixed now and they have unified design which i like no Bottom border for the panels under tabs which clean. I think the option (hidden) on the panel configuration has no utility now will that option be omitted hence it doesn't serve any purpose anymore!

Many thanks for such rich feature, looking to see such tab implementation for relationships panels in the future. 
Thanks for your work again.
<img width="1470" alt="Screenshot 2022-07-17 at 14 21 43" src="https://user-images.githubusercontent.com/19490674/179400649-f7d9421a-f816-4a89-943f-954f908ee647.png">

**Comment by yurikuzn** [comment]
It's a legit behavior. Anyway backend validation will cause the error not allowing to save. Admin should make sure there are no such collisions.

**Comment by Kharg** [comment]
Tooltip text is not shown correctly @yurikuzn 
![immagine_2022-09-05_232335734](https://user-images.githubusercontent.com/32223252/188513548-6fc46c5f-20ad-4385-bc42-98c0c5686c71.png)

**Comment by gustavo-dssi** [comment]
> Tooltip text is not shown correctly @yurikuzn ![immagine_2022-09-05_232335734](https://user-images.githubusercontent.com/32223252/188513548-6fc46c5f-20ad-4385-bc42-98c0c5686c71.png)

Hey @Kharg 
where do I find this option? thx

**Comment by Kharg** [comment]
@gustavo-dssi On Espo 7.2.0 in the Entity Layout settings (Detail view)

**Comment by yurikuzn** [comment]
Administration > Entity Manager > {Entity} > Layouts > Detail > edit panel (pencil icon).

**Comment by admin0o0** [comment]
Entity "User" does not display correctly if the multi-label panel is enabled
