### ISSUE TITLE
Overdue filter for every Event Entity

### ISSUE THREAD

**Issue by Kharg** [espocrm/espocrm#2396]
It would be useful to have the Overdue filter for every Event entity (also the custom one) instead of only for Tasks.
Also it would be useful to be able to select filters in the "My Activities" dashlet.

**Comment by yurikuzn** [comment]
Meetings and calls can't be overdue.  BTW it's possible with advanced pack to have custom filters.

**Comment by scotlad9** [comment]
Hi Yuri.  I had posed this as a question on the Espo Forum and Kharg kindly responded.  In a situation where a user has 20 calls scheduled for a particular day but, due to circumstances, can only make 10 of these calls, the remaining 'overdue' calls no longer show on the 'My Activities' dashlet.  You can partially get round this by using the Record List dashlet with 'status = planned' but this of course shows future calls too not just the ones that have been missed.  Same applies to meetings and custom entities.  I think this would be a useful enhancement and I have used other CRMs in the past where activities are listed as 'pending' until 'completed'.

**Comment by yurikuzn** [comment]
Google search:

* `"overdue calls" crm` – 343 results
* `"overdue meetings" crm` – 104 results
* `"overdue tasks" crm` –  30,400results

If I now added a filter with such a name, it would be left there forever. Do we really need there such a filter with such a controversial name?

The option for the dashlet to display past activities would be more appropriate solution for this.

**Comment by rabiibrahimi** [comment]
i would agree with you @yurikuzn on this. i think it is controversial name for calls and meeting and probably it is best to keep the user in control if they wish to add such filter. on the other hand enhancing the dashlet activities to optionally show past activities is a good option, also would be nice to add status field on the row to show status of each activity. 

I think what is missing for activities is recurring option, it would handy to have an option to make Task / Call and Meeting recurred. recurring activities are more required features than overdue.

**Comment by yurikuzn** [comment]
Added displaying of past calls in my calls dashlet: https://github.com/espocrm/espocrm/commit/41b92c9ee15716057b4242e3299ee47d664ad654. The dashlet allows changing the layout, so any field can be added.

**Comment by scotlad9** [comment]
Hello Yuri

Thank you for doing this.  Once more I would like to offer my sincere thanks to you and the team for all your hard work in developing such a great, easy to use product.

I hope you, your family and friends are all safe and well in what must be extremely difficult times.

Best regards
David
David Pettigrew
m:    07703 040025
t:     0131 440 0770
e:    ***@***.******@***.***>
