### ISSUE TITLE
Interesting code discoveries

### ISSUE THREAD

**Issue by MetroConductor** [espocrm/espocrm#2594]
I was looking into enhancing the core of EspoCRM, and I noticed this some things - in example, the definition of a ID field/column - are defined several times, overwriting each other. There's also curious cases of functions being deprecated, even although they are still in active use and no replacement appears to be available. Finally, I'd like to remark that some odd choices have been made regarding data design; why are the currency codes used as index for the currency table?

**Comment by yurikuzn** [comment]
> the definition of a ID field/column

> There's also curious cases of functions being deprecated, even although they are still in active use and no replacement appears to be available.

> I'd like to remark that some odd choices have been made regarding data design

Provide concrete examples please.

> why are the currency codes used as index for the currency table

What's wrong with it? This table is fully cleaned and populated when rebuilding.

**Comment by rabiibrahimi** [comment]
hey 

i have noticed same especially when i was writing some hooks and had to dive in BaseEntity found few methods deprecated but are still used i thought that it was only my editor but it is worth sharing with you. 

1 - populateFromArray is deprecated https://github.com/espocrm/espocrm/blob/be27fc45eec1abbd0d159891f3634eb19edb6218/application/Espo/ORM/BaseEntity.php#L222
2 - both these use valuesContainer which is deprecated https://github.com/espocrm/espocrm/blob/be27fc45eec1abbd0d159891f3634eb19edb6218/application/Espo/ORM/BaseEntity.php#L164  
https://github.com/espocrm/espocrm/blob/be27fc45eec1abbd0d159891f3634eb19edb6218/application/Espo/ORM/BaseEntity.php#L172
3 - this method is not defined according to my code editor (findRelated) 
https://github.com/espocrm/espocrm/blob/be27fc45eec1abbd0d159891f3634eb19edb6218/application/Espo/ORM/BaseEntity.php#L298

I  hope my code editor is right and we are not wasting your time Yuri. 

Thanks

**Comment by di-rect** [comment]
I have seen the same, it seems to be a lot of legacy where code is not cleaned up propery when code is moved up a level higher for an example.

 > > why are the currency codes used as index for the currency table
> 
> What's wrong with it? This table is fully cleaned and populated when rebuilding. It's being joined by the currency code.

This is very bad design for a relational database. The same as I don't agree with the "unique ID" generation - which is a real issue when you want to host your app in a HA-way  - there should be used something like UUID's in that case, V4 is the best example you can get there, not stored as varchar(36) as doctrine likes but as binary(16) as it should be.

This could be a great advantage to have.

**Comment by yurikuzn** [comment]
> This is very bad design for a relational database. 

Can you elaborate why 3-letter unique code as a primary key is very bad? We will change length to 3, it was a miss that it's set to 36.

>  should be used something like UUID's in that case

It's a few lines of code to customize it to be UUID now.

**Comment by yurikuzn** [comment]
A method is deprecated means it's not supposed to be used by 3rd party code. A method is not removed because it's used in extension and we have to support it for quite a while. A method may still be used inside the app for the sake of avoiding code duplication. It will be moved away later.

There are always ways to achieve the same w/o using deprecated methods.

> populateFromArray

Use `set` method.

> valuesContainer

Use methods to access data. We don't use public properties anymore as they can't be interfaced. 

> findRelated

See ORM docs. You need to use ->getRelation()->where(..)->find();

**Comment by rabiibrahimi** [comment]
Thank you for your explanation. it make sense now, appreciate your time and effort to reply to our questions. 
Many thanks

**Comment by di-rect** [comment]
> > This is very bad design for a relational database.
> 
> Can you elaborate why 3-letter unique code as a primary key is very bad? We will change length to 3, it was a miss that it's set to 36. It's a utility table not supposed to be used directly. The sole purpose is is inline currency conversion. The CHAR(3) is a good choice for primary key. When one say "this is very bad design" I expect to hear some reasoning with it.
> 
> > should be used something like UUID's in that case
> 
> It's a few lines of code to customize it to be UUID binary now. I added this ability specially for such cases. Please use it.
> 
> Espo is a product first, not a framework. It's already in use by many companies, often by small ones w/o tech specialists. We can't change ID column type/length now as it can cause problems for many. As we don't have control what IDs they have.
> 
> > but as binary(16) as it should be.
> 
> Please, no need absolutisms "it should be".

Try to read about database design and performance, lots of products are poorly designed (because of legacy) and it has nothing todo with a framework, actually you created some sort of it so I assume you like to work strictly. Nothing else like "should be" exists then, these (column)types are designed for it.

Can you also explain why you have your own querybuilder next to Doctrine ? Why no wrapper around Doctrine ? Is that maybe legacy as well ?

**Comment by di-rect** [comment]
> Code is not removed because of backward compatibility needs. There shoulbe no any code not cleaned up unless its used by some extension. The statement "a lot of legacy not cleaned up properly" is not true.

Sometimes people need to move on, so you need to force 3rd parties to update their code, you are nog responsible for that; unless it are your customers but even then, you cannot support forever, it makes your codebase a mess in some time.

**Comment by yurikuzn** [comment]
> Try to read about database design and performance

It won't gain any performance. The *currency* table will always have one to few records. CHAR(3) should be faster than BINARY(16). The discussion about the Currency table and bad design is pointless and farfetched

> Try to read about database design and performance,

This not an argument.

> Can you also explain why you have your own querybuilder next to Doctrine ? 

ORM was written 10+ years ago, not specifically for Espo. When we started developing Espo, Doctrine didn't have some features we needed right there as we were in hurry. We had a choice, either customize Doctrine (with potential future compatibility issues) or use the existing ORM ready.

> Sometimes people need to move on, so you need to force 3rd parties to update their code,

Move on to where? Having some classes and method deprecated is not a big deal. Check doctrine DBAL repository, they have the half deprecated.

We value our business needs more than having an ideal codebase w/o deprecated code.

> it makes your codebase a mess in some time.

Can you provide examples of mess?

**Comment by di-rect** [comment]
You aks a lot an I understand why, this project has grownout standards with lots of reasons. you ask me to point out. I personally will never use Doctrine because of all it's issues it has, overhead and so on. If you want examples, there are already give some easy ones, the rest is just a way of design choice; being in a "hurry" never ended good in IT, see the result which you never have tried to refactor it seems. For that reason there is no reason at all to give more examples, Espo IS the example.

I'm actually thinking of a rewrite, it's not that hard if you look it overal, this on a enterprise framework makes it even easier. Database design is the (performance) standard you will design, and if you state that CHAR(3) is faster (in the mass) then something that is already binary you didn't understand how database servers work to start with and that is a pity.

I don't say you did completely wrong, I just don't see why things aren't fixed properly and are in some way pretty Duct-taped because of knowledge or some time/lazyness which makes it pretty messy as you actually describe yourself.

**Comment by yurikuzn** [comment]
> being in a "hurry" never ended good in IT

You hardly find somebody not in-hurry in IT.

> see the result which you never have tried to refactor it seems

I refactored almost the whole codebase, including code written by others, and actually find the current design pretty solid.

> I'm actually thinking of a rewrite, it's not that hard if you look it overal

It will take years to write a comparable product.

> and if you state that CHAR(3) is faster

I don't ask you proofs, as I'm sure you won't provide any.

**Comment by yurikuzn** [comment]
Current table always has a few records. Saying that it's "very bad design" to use 3 letter currency code for indexes is way farfetched. Discussing this took more time than any possible performance gain for every  Espo instance added up multiplied by million.

> Also, you won't provide me the opposite it seems

CHAR(3) takes 12 bytes, UUID BINARY takes 16 bytes. When database uses indexes it operates with binary values when JOIN-ing. Am I wrong?

**Comment by di-rect** [comment]
> The Currency table always has a few records. Saying that it's "very bad design" to use 3 letter currency code for indexes is way farfetched. Discussing this took more time than any possible performance gain for every Espo instance added up multiplied by million.

Yes I understand you and the reason why I say: standards. It will help you more then just thinking you are doing better then standards.

> > Also, you won't provide me the opposite it seems
> 
> CHAR(3) takes 12 bytes, UUID BINARY takes 16 bytes. When database uses indexes it operates with binary values when JOIN-ing. Am I wrong?

Have you thought about what I said ? Char needs to be converted to binary first (under the hood tho), unhexed UUID is already binary if you do it on the PHP side, and you want it binary there because it makes your application overall faster, why ? Everything is binary at the end. Try to test that ones, you will be amazed, and yes indexes help even more there, that's why you store UUID as binary.

Then I don't talk about buildin UUID functions yet for MySQL 8, searches, compares, selects, all much faster. Again why ? It's designed for it, that is why you design databases and some people make their jobs out of it because that fact. Did they ever added extra function for CHAR ? No, for UUID they did, made it better and better because of it's known use, and with succes! Check you URLS these days, UUIDv4 is the way to go, even there.

When you look at the combination of PHP and MySQL on you app in that case you start to understand why PHP-FPM has been designed, you can make it peformant, balance then h*ll out of it that way too; because of overall design off you app from the start.

**Comment by yurikuzn** [comment]
> Char needs to be converted to binary first

When we are joining tables by indexed columns, they (indexes) are stored as binary values. Does it matter if any collation MySQL assigned to them? If binary values are used inside. Joining is a bottleneck in apps like CRMs that's why I'm talking only about them.

**Comment by di-rect** [comment]
> > Char needs to be converted to binary first
> 
> When we are joining tables by indexed columns, they (indexes) are stored as binary values. Does it matter if any collation MySQL assigned to them? If binary values are used inside. Joining is a bottleneck in apps like CRMs (a lot of data, not many users) that's why I'm talking only about them.
> 
> EDIT. The difference is that binary takes less size. But we were talking about CHAR(3) vs BINARY(16).

It still needs to be converted first, you put it in as a string, with UUID you put in Binary as you use binary unless you need to representate the UUID somewhere; which is stil the best approach when it comes to using public unpredictable ID's as well. And indeed because of joins you use indexed BINARY(16) UUID, I use lots of joins because of reference tables.

Also, a character is 8 bytes, 3x8=24 vs Binary(16)

You can't debate this further, I explained it well enough; it's just bad design; sorry!

**Comment by yurikuzn** [comment]
> a character is 8 bytes, 3x8=24 vs Binary(16)

Here you failed.

**Comment by di-rect** [comment]
> > a character is 8 bytes, 3x8=24 vs Binary(16)
> 
> Here you failed.
> 
> What a waste of time for me. ... And, shouldn't have posted from a different account to gain an upper hand.

Yes sorry, you are right there, but you didn't provide the SQL evidence yet. Start with that, maybe you fail even harder. (I'm sure you do because you never talk about real performance anymore)

But be honest, you don't use standards, they are made for a purpose and that's where you are failing all over the place. You are comparing apples, oranges and bananas and try to diliver an enterprise fasioned application.

You think your time might be wasted but you started thinking and finally "catch" me on something I'm honest about calculated wrong.

You are, and maybe, will never be honest about that you don't understand standards; so you lose at any point at then end.

Try to be honest, it will help you app become better (maybe).

**Comment by yurikuzn** [comment]
You presented yourself as a specialist in the area. Expected to learn something for you. But only get incoherent information. But such a big mistake. It's hardly believable it's just a mistake but not an ignorance. mb3, mb4... you should have known it.

**Comment by yurikuzn** [comment]
I wrote you yesterday that tested binary IDs and it indeed was bit faster (15%) on hard joins.

Regarding inserts, it want give any gains.

Regarding :standards". What standard? When we started Doctrine DBAL even didn't have BINARY supported. Call every APP using doctrine back than bad design. Well, i'm wasting time.

**Comment by di-rect** [comment]
> You presented yourself as a specialist in the area. Expected to learn something for you. But only get incoherent information. But such a big mistake. It's hardly believable it's just a mistake but not an ignorance. mb3, mb4... you should have known it.

You are a joke, you can't handle right critism and you are not honest; you prove that.

People make misstakes but you do all over you application where I admit a wrong calculation, I don't care either.

You try to tell the world your way is better then standards and ignore everything after someone was right about you being wrong there.

At least I understand, and I hope others as well, how you react on the slightes misstakes you make in your life; pity.

Good luck with all that; it's all I can wish you.

**Comment by yurikuzn** [comment]
> I admit a wrong calculation,

It was not a calculation error, but assuming that bytes in mysql takes 8 bytes;

> You try to tell the world your way is better then standards 

I never said our way is better (actually this part was not initially designed by me). I only said that it would be a BIG issue to migrate existing users. Hence, considered having the ability to have UUID as an option that can be turned on. You could help  by trying to implement it as PoC, I provided some input.

But you nitpicked over the currency table. And didn't admitted that your critique there is completely off.

Learn to criticize and restrain to resort to ad hominem.
