### ISSUE TITLE
Canceled calendar entry goes over 2 days

### ISSUE THREAD

**Issue by ChrisSka** [espocrm/espocrm#2850]
I have set the crossed out line of a canceled calendar entry in the CSS file to red, so you can see it better.
But there you can see that this line goes over 2 days, although the entry is only set for one day. respectively it is not even a whole day event, but only for a few hours.
With the standard white line you can't see it at all, because of the white background.
![Screenshot 2023-09-14 15 47 27](https://github.com/espocrm/espocrm/assets/68166740/e77a16a0-ccbb-4a1c-9b08-e765335057ac)

Just tried a dark theme and see the problem.
The entry is not shortened.

![Screenshot 2023-09-14 15 47 01](https://github.com/espocrm/espocrm/assets/68166740/ba2e3ca0-9d73-4772-a0af-55fb6a6f1dde)

**Comment by yurikuzn** [comment]
Please, don't erase the whole Bug-Report template text.

**Comment by ChrisSka** [comment]
But the dark theme is the one from EspoCRM, so not a customized one.
There are no instructions for reproducing it, so I had deleted the text.

Until version 7.5.6 it worked normally, there I had also set the dash to red and only the one entry was crossed out, respectively it did not go over 2 columns.

**Comment by yurikuzn** [comment]
Reproduced. I will take a look when get a chance.

**Comment by yurikuzn** [comment]
Steps to reproduce example:

1. Open calendar tab, switch to "Shared" view.
2. Create an event with the long name.
3. Observe name is being overflown.

*Shared view* was a key point in reproducing.

3/4 of bug reports we get are turn out to be false. When we receive a bug report w/o steps to reproduce, can't reproduce it (trying multiple ways), especially seeing the UI is customized, we automatically tend to assume this falls into 3/4 of false bug reports. That's why explicit steps to reproduce with the provided version number are so important. Erasing the whole bug report template is welcomed.

**Comment by ChrisSka** [comment]
Thanks, was fixed with last update, although the solution was not planned at all.
