### ISSUE TITLE
Config override

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2916]
* Config files not writable by Espo.
* Should override parameters of the standard configs.
* Supposed to be written manually.

Two config files:

* `config-override.php`;
* `config-internal-override.php` – to store sensitive parameters.

**Comment by arkadiyasuratov** [comment]
I imagined `config.d` to be a folder with lexicographic order. Throw in some glob, loop function, and recursively merge arrays. Besides the overriding log handler or file storage, this would allow us to protect sensitive values such as passwords and tokens, preventing their exposure in environment variables visible to other processes.

**Comment by yurikuzn** [comment]
I'd avoid deep array merging to be more straightforward.

Not sure about multiple files. Maybe we could start with a simple single `data/config-override.php`.

**Comment by yurikuzn** [comment]
Another question. Should parameters be considered internal (as for config-internal). Or rely on access level defined in metadata > app > config.

**Comment by moltar** [comment]
> Should parameters be considered internal

I think this can be either by convention (file naming) or some flag inside the config.d config file. E.g. if the `internal` flag is set, merge it with the internal config.

**Comment by yurikuzn** [comment]
You'd be able just use getenv PHP function inside config-override.php.

**Comment by moltar** [comment]
> You'd be able just use getenv PHP function inside config-override.php.

Sure, that'd work as well.

**Comment by moltar** [comment]
Meanwhile, I came up with a solution that solves some of my pain:

A config writer script that accepts JSON object, and writes it to config.

## `./config-writer.php`

```php
<?php

require_once('bootstrap.php');

$app = new \Espo\Core\Application();
$config = $app->getContainer()->get('config');

$injectableFactory = $app->getContainer()->get('injectableFactory');
$configWriter = $injectableFactory->create('\Espo\Core\Utils\Config\ConfigWriter');

$configWriter->setMultiple(json_decode('{"awsS3Storage":{"bucketName":"foo-bar"}}', true));
$configWriter->save();
```

The value can be sourced from anywhere, e.g. environment or you can static write the JSON to file and deploy it with the app.

## Usage

```sh
$> php config-writer.php
```

**Comment by bandtank** [comment]
> A config file (or maybe files) not writable by Espo.
This is a great idea. it can be confusing to know how to force certain behaviors, so a place that you know Espo can't touch would be useful.

> Should override parameters of the standard configs.
Yes, this would be essential.

> Don't allow Espo to write parameters already defined in the config-override (?). Throw exception (?).
I don't like the first suggestion. Espo should be able to write values to Espo-managed config files even if the fields are defined in a non-writable-by-Espo config file. I would also not want an exception to be thrown because the behavior may be desirable. In my opinion, writing a warning to the log would be sufficient.

**Comment by bandtank** [comment]
> A config file (or maybe files) not writable by Espo.

This is a great idea, but there are some potential issues.
* Modules may need to define configuration parameters that Espo can't touch. How would precedence be decided on a per-file or per-field basis? E.g., timezone may be set for the instance and then set again for the module. If both files are custom, which timezone is used?
* How would the UI respond to the existence of non-writable fields? Say the timezone is included in a non-writable config file; would the admin setting for system timezone become read only.


> Should override parameters of the standard configs.

Yes, this would be essential.

> Don't allow Espo to write parameters already defined in the config-override (?). Throw exception (?).

I don't like the first suggestion. Espo should be able to write values to Espo-managed config files even if the fields are defined in a non-writable-by-Espo config file. I would not want an exception to be thrown because the behavior may be desirable. In my opinion, writing a warning to the log would be sufficient.

**Comment by yurikuzn** [comment]
> I would not want an exception to be thrown because the behavior may be desirable. 

I came to the same conclusion.

For now, I want to implement support of two additional config files:

* config-override.php
* config-internal-override.php

This is the minimum for having the override functionality and is straightforward. These files are supposed to be written only
 manually.

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/525397e64d1ddcf65cd8ae58486931f74b96214c
