### ISSUE TITLE
AGPL license

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#2932]
We are changing the license to AGPL. See the [blog post](https://www.espocrm.com/blog/espocrm-license/).

**Comment by arkadiyasuratov** [comment]
Since extensions are not considered independent and separate works, they cannot be used without EspoCRM, does it mean developers must also relicense their extensions to AGPL when version 8.1.0 is released, just like WordPress requires in its [guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#the-guidelines)? If that's the case, will you also relicense your extensions?

In the blog post, you said you want to "prevent larger companies from developing a SaaS based on our product." However, AGPL is broader; it covers use over the network. How should big companies follow the new license terms? For instance, when a parent company gives access to the instance to its subsidiaries, or when a government institution gives software to other government bodies. How should they provide the source code for the user interacting with the instance?

**Comment by yurikuzn** [comment]
AGPL is the same as GPL plus the additional 13 section. Only copyright holders can require releasing derivative work under GPL/AGPL. Only authors of EspoCRM can require a developer to abide to copyleft terms. As we had CLA allowing us to re-license contributions, any contributor (past or future) cannot force a developer of derivative work to release their work under GPL/AGPL.

AGPL is broader than we might need. But there's no middle ground license between GPL and AGPL, that would have been approved as open-source OSI. We could have created a new license, but that would not non-open-source.

But all GPL licenses allow us to provide exceptions to specific users (as long as those exceptions give more rights but don't restrict). If a company has a policy about using GPL or AGPL (big companies often do), we can provide exceptions for them. For a peace of mind or for a legal safety. We could sell exceptions for a symbolic price. Also we might release EspoCRM under the second license in the future. The same code but a different license.

If the case you described, according the AGPL, the company should have some way to provide access to source code of modifications to its subsidiaries. But would we have an interest to force the company to do it? We would only if they are SaaS provider, if they took EspoCRM, invested to extend it and became our direct competitor.

Regarding extensions. GPL exceptions could give permission to release extensions under a commercial license as well as don't be bound to the Section 13 of AGPL. We are not interested into forcing developers to release their extensions under GPL/AGPL. The same as we didn't force them to release under GPL before. When we will have the second license (commercial or source available, not sure), there will be an additional way for developers to release their work under non-GPL/AGPL license, without needing an exception from us.

**Comment by yurikuzn** [comment]
Regarding "How should they provide the source code". This is a difficult question, personally, I can't answer fort sure, the license text is vague here. Nevertheless, you should not be worried about it, unless you are intended to build a real SaaS. We're not open-source purists. If anyone will be concerned about licensing, please contact us via the website form. We gonna have a dual license or introduce exceptions soon for such cases.
