### ISSUE TITLE
make OIDC auth processing in the same window instead of a pop-up window

### ISSUE THREAD

**Issue by vladimirdulov** [espocrm/espocrm#2958]
Currently OIDc auth implementation looks unfriendly.

`Sign in` button opens a pop-up window. Most browsers block popups by default, others are showing a little warning that a pop-up window was requested. Most of the users won't notice and can't log in!
When you accept the pop-up opening a window appears, but password managers like Bitwarden don't show and you can't login easily.
After that if you manage to fill in the credentials you get a strange warning:
```
If this window is not closed automatically, it's probable that the URL you use to access EspoCRM doesn't match the URL specified at Administration > Settings > Site URL.
```
If you close this pop-up and try to login again you're suddenly logged in.

Could you amend the implementation so all these OIDC authentication is being processed in the same window.
Most of applications do OIDC auth in the same window out of the box, some others provide an option - a pop-up window or the same window.

**Comment by gramakri** [comment]
We got this report after we published the Cloudron EspoCRM package to use OIDC instead of the previous LDAP. https://forum.cloudron.io/topic/10906/serious-oidc-espocrm-issues/ has more context for the original user report.

**Comment by yurikuzn** [comment]
> Most browsers block popups by default, others are showing a little warning that a pop-up window was requested. Most of the users won't notice and can't log in!

I believe Chrome does not block by default. We just tested on different PCs. It could be why haven't received any complains yet as it's a most popular browser. Anyway, I'll consider re-implementing. 

> If you close this pop-up and try to login again you're suddenly logged in.

This could by a Firefox only issue. But once you enabled, it should work OK afterwards.

**Comment by yurikuzn** [comment]
On Safari the popup didn't close? It did when we tested. But it required to allow popups.

**Comment by vladimirdulov** [comment]
Yes, it doesn't close with these settings on Safari:

![Screenshot 2024-01-25 at 16 59 33](https://github.com/espocrm/espocrm/assets/144679/c0768f71-d8d1-4360-a70b-78bb6cab2f51)

**Comment by yurikuzn** [comment]
Ok. Thanks. Might be differs depending on time between user interaction and a popup is requested to open.

**Comment by yurikuzn** [comment]
It tuned out that whether popup is blocked depended on time between a user interaction (click) and popup being opened. Since we had a request to the backend, it could take some time and some browsers may block or not block. No need to re-implement re-direct. This fix should work for all. Now we display an empty popup first, then load it when all data is ready.

https://github.com/espocrm/espocrm/commit/e95fcc6532ca601af104857efd2b86fe7e872a70

**Comment by dustyhansen** [comment]
@yurikuzn this is still an issue for me that I am running into today. I am using OIDC with Discord as a Portal authentication method. Because you do OIDC in a popup window rather than a full-page redirect, it calls the Discord app for authentication and the nonce is not passed back to the browser so the login fails. If the user is not logged into Discord in their browser, but has the Discord app open on their computer, it will not log them in.
