### ISSUE TITLE
OIDC auth popup doesn't authenticate user at once

### ISSUE THREAD

**Issue by vladimirdulov** [espocrm/espocrm#2959]
In the opened pop-up window when you filled in the credentials you get the following strange warning and can do nothing.
```
If this window is not closed automatically, it's probable that the URL you use to access EspoCRM doesn't match the URL specified at Administration > Settings > Site URL.
```
If you close this pop-up and try to click `Sign In` button in the main window again you're suddenly logged in.

**Comment by gramakri** [comment]
We got this report after we published the Cloudron EspoCRM package to use OIDC instead of the previous LDAP. https://forum.cloudron.io/topic/10906/serious-oidc-espocrm-issues/ has more context for the original user report.

**Comment by yurikuzn** [comment]
I think it's configuration issues. It should not work like that. It should log out well, it should close the popup automatically.

**Comment by vladimirdulov** [comment]
just tried to set oidcAuthorizationPrompt to 'login', was unset before (default  'consent'). It seems to work a bit better.
But anyway if popups are blocked in browser, the popup window doesn't close itself.
tested in Safari v17.0, Firefox v121.0.1, MacOS.

**Comment by yurikuzn** [comment]
Not closed popup may happen when the browser blocked the popup. It's how some browsers behave, not returning the proxy object if the popup blocked but then allowed by a user. If the user allows popups for the website, it should work after the page refresh.

Regarding logout, it should work if the logout redirect configured.

I'll consider implementing redirect instead of popup in the future. I'm closing this issue and going to create a new one when will tackle the implementation. I don't like having a reference to a report with UPPER case usage, exclamation marks, words "serious", "useless" etc, especially when it's a free feature that . Luckily, they are pretty rare in our community.

**Comment by gramakri** [comment]
@yurikuzn co-founder of Cloudron here. thanks for considering implementing a redirect.

I am with you that such language is unnecessarily distracting. I have removed our forum link which is the place where the language is used. This bug report doesn't have the language, in case you want to consider keeping this issue.

**Comment by yurikuzn** [comment]
No problem with the issue. We'll investigate and then provide more info.

**Comment by yurikuzn** [comment]
Regarding auth log and not being able to see a user. The logged user is available here:

![image](https://github.com/espocrm/espocrm/assets/1006792/ba92e010-7dbd-4df8-9ba6-13e8786cd9fc)

**Comment by yurikuzn** [comment]
Resolved: https://github.com/espocrm/espocrm/issues/2960
