### ISSUE TITLE
List view pagination

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#3018]
Functioning together with 'Show More' button.

Available on:

* Main list views;
* When viewing related records (not on panels).

Abilities:

* Going to the next/previous page;
* Going to the first/last pages;
* Jumping to a page by number.

**Comment by Kharg** [comment]
Hi Yuri,

I tested pagination with an older 8.2.0 build.

I was wondering, why not having pagination buttons both at the top and at the bottom of the page? Instead of having the buttons only at the top?

It would be easier to change pages if many records are loaded.

Example:

![image](https://github.com/espocrm/espocrm/assets/32223252/b81442df-f4db-4a3a-8158-57423154944f)


The current implementation is fine, this is just an idea from other designs I have seen.

Thanks.

**Comment by yurikuzn** [comment]
1. Show more button is there.
2. No reason when the bar is sticky.
3. There are systems where the pagination is on only on top with a sticky bar.

**Comment by yurikuzn** [comment]
I spent multiple dozens of hours on it. There was many many issues to handle. It won't be changed now.
