### ISSUE TITLE
Bug in Team Display for Demands: Multiple Teams Displayed Instead of Default Team

### ISSUE THREAD

**Issue by fedikhaled** [espocrm/espocrm#3216]
Describe the bug
When creating a demand in EspoCRM, the "Équipes" (Teams) field sometimes displays multiple teams for the same demand instead of only the default team assigned to the user who created the demand. Additionally, in some cases, unrelated teams are shown.

To Reproduce (MANDATORY, DO NOT REMOVE)
Explicit steps to reproduce the behavior:

Create a user and assign them multiple teams with one default team.
Log in with this user and create a new demand under "Demandes S.controle."
Check the "Équipes" field for the created demand in the demand list.
Expected behavior
The "Équipes" field should only display the default team of the user who created the demand.

Screenshots
Screenshot provided showing the issue where multiple teams appear for the same demand.
![equipes](https://github.com/user-attachments/assets/004f940f-eaae-4363-b153-cb7ad82ac0ea)

EspoCRM version
Version:  7.3.4 .

Additional context

The issue occurs regardless of whether the user belongs to multiple teams, as long as they have a default team assigned.
Database and entity definitions have been verified, and the issue persists.
Tested on both newly created demands and existing demands.

**Comment by arkadiyasuratov** [comment]
Your version is quite old, so the first step is to update EspoCRM to the latest version. Make sure the steps to reproduce the issue use built-in entities like Accounts, Contacts, or Opportunities, not custom ones. Also, try to reproduce the issue on the official demo, which is always up to date.

If you can’t update because of compatibility issues and need a fix, the forum is the best place to ask for help.

**Comment by yurikuzn** [comment]
I'm almost sure it's due some customization or automation. As I'm personally use Espo everyday with multiple teams and one default, I believe we don't have such a bug. If new input come, I may re-open the issue.
