### ISSUE TITLE
Case: Automatically followed by portal user if contact is specified

### ISSUE THREAD

**Issue by yurikuzn** [espocrm/espocrm#358]

**Comment by yurikuzn** [comment]
https://github.com/espocrm/espocrm/commit/20f15e749e6f9ed4203d1424177765ebec9ae63e

**Comment by rodrigoscoelho** [comment]
Why not this for a regular system user? Only for Portal???

**Comment by yurikuzn** [comment]
It's by Contact field.

**Comment by rodrigoscoelho** [comment]
Yuri,

Actually, the way I'm adding following people on the object is by creating
a group with several users, and adding the group on the Teams field.

This will add each person on that group as following. The problem is that
sometimes it doesn't happen as expected. So I have to edit the team, delete
the Group added, and add again.
Doing this like 3 times it will work. I don't know Why.

I don't know either if this is a bug that I'm using to fill my necessity or
not.

Please make it official. At least this way I mentioned above.

Thanks

**Comment by yurikuzn** [comment]
It's not supposed to work. Adding team doesn't make users to follow. I have no clue how it could work.

**Comment by rodrigoscoelho** [comment]
So please, I really would like to have a feature like that.

It is not common to force each user to ADD himself to each project. You
could have a Manager with possibility to add users on the following list.

Maybe other users would like the same feature. The problem is that only few
follows the GITHUB requests. :(

**Comment by yurikuzn** [comment]
There are some issues with this feature. You can use workflow 'Make Followed' action for the present.
