### ISSUE TITLE
Continuous deployment (build process) setup

### ISSUE THREAD

**Issue by tannakartikey** [espocrm/espocrm#446]
Once we clone the repo we can work in the development environment and generate the build.

Once the build is deployed on the production, how do we deploy next changes to the server without breaking the code or losing the data?

I would like to set up the staging and the production and frequently would like to import the data from the production to the staging.

I could not find anything regarding this in the documentation or on the forum.

**Comment by yurikuzn** [comment]
It's a good question. Since we usually have some scripts in upgrade packages I'd suggest using our upgrades. But there can be problems if you have modifications in core files

**Comment by tannakartikey** [comment]
Thanks for the answer @yurikuzn
Do we have them documented in any form or I'm supposed to go through the code to understand them?

I would like to work towards it since it is an essential part of the SDLC

**Comment by yurikuzn** [comment]
Seems I missed the point. I meant to upgrade your inctance in regular way using Administration > Upgrades. That's only only way we support.

@alasdaircr, maybe you can give some advices? I believe you have experience with this. Thanks.

**Comment by bandtank** [comment]
@tannakartikey are you trying to deploy to an HA environment? If yes or if you're trying to deploy to any environment that depends on a stateless server, it won't work. EspoCRM was not designed to scale horizontally to an HA or stateless environment. I'm working on a fork of the repository that will fix this issue and basically turn it into a more commercial product, but it's going to be a while. Just FYI.

What you're trying to do is a really typical build and deploy process, but you have to do it in place on the same server each time with downtime. As I mentioned above, all of the uploads, preferences, and whatever files you store in the application will end up on a disk instead of at an object store like S3. 4.5.0 introduced a fileManager class that is supposed to help move objects off of the local server, but there are many more issues that prevent a typical app deployment. This also makes it basically impossible to make a reliable backup of the local files, which is the primary and major issue with how files are currently handled.

The short answer is plan for downtime and try to deal with the consequences of the server maintaining your files and application's state. There's no way to run this application through a build pipeline because of all the dependencies that aren't saved outside of the actual application's installation directory. If you find a way to do this, please let me know. As I said, I'm working on it right now because the rest of the application is good, but it can't be used in any kind of scaled or HA environment.

Note: you can deploy the data/config.php file with a typical deployment process, so if you can figure out how to handle all of the other types of files that need to exist locally, then you can do a real deployment.

**Comment by tannakartikey** [comment]
@bandtank no, I am not trying to scale it up. Planned downtime is also fine with me.

I am also fine with zipped upgrades. 

@yurikuzn how do you generate the zipped upgrades?

**Comment by yurikuzn** [comment]
We have version tags in git repository.

1. We build with command:
```
grunt
```
2. Create upgrade packages with:
```
node diff VERSION_TAG
```
It will generate upgrade in build dir that you will need to zip.

If there were some significant changes that can't be processed just by files replacement we write afterUpgrade or beforeUpgrade scripts manually and include them into upgrade package.

**Comment by bandtank** [comment]
@tannakartikey How do you plan to backup your uploads directory?

**Comment by bandtank** [comment]
For anyone else who gets here wondering how to actually do a release because the documentation doesn't say how to do it, here are the complete instructions. This assumes you have already installed ```composer```, ```npm```, and ```grunt```. If you haven't installed any of those things, do that first.

1) ```git clone https://github.com/espocrm/espocrm.git```
2) ```composer install```
3) ```npm install```
4) ```grunt```

At this point, you should have a build in the build directory called ```EspoCRM-4.5.0```. The version number is from ```package.json``` and you will need to change it to do an upgrade build. As of right now, master is only a few commits ahead of 4.5.0, so the upgrade will have the files from only those commits.

Change the version in ```package.json``` to "test" and then save the file. Now run grunt again and you should have a folder in ```build``` called ```EspoCRM-test```. If you look through the files in that folder, you'll see all of the files from the current commit.

Note: edit ```diff.js``` and change ```require('sys')``` to ```require('util')``` as it is newer and will prevent the process from producing warnings.

To generate the upgrade, you have to produce a diff against the last git tag, which is what was meant by VERSION_TAG, which was unclear. This means you'll have to tag your commits if you want to produce upgrade files. In this case, run ```node diff 4.5.0```, which will create a folder called ```EspoCRM-upgrade-4.5.0-to-test``` in build. I haven't tried the next part yet, but I believe you are supposed to zip the ```EspoCRM-upgrade-4.5.0-to-test``` folder and then upload it through the administration area of the website.

**Comment by arkitechtura** [comment]
@bandtank Thanks a lot for your insight about the build process. In my case, I am starting to familiarize with the product, which I find very good both visually and functionally. However, I've been struggling on how to move a set of customizations from one installation to another. In a forum post, someone suggested to copy over the 'custom' folder, but that is not working for me. Do you know where customizations finally end up in the file system and/or the database, so I can move them from server to server?

**Comment by bandtank** [comment]
@arkitechtura The biggest problem is how preferences are stored. There was no reason to develop the software in such a way that preferences were stored in a file instead of the database, but that's what we have to deal with now. Individual users have to login to the same server to get the same preferences each time. I'm working on storing that stuff in a database specifically so the server can become stateless. Otherwise, this app absolutely can't be used in any environment without either customized and complicated routing to make sure sessions are sticky or you don't care about user preferences being consistently applied, which is obviously bad.

There are a lot of other files that shouldn't be files as well (by that I mean they should be in a database), but at least that stuff can be handled consistently with a proper deployment process. It's pointless extra work, but there are workarounds. What I've been doing is merging updates to the main repository into my own branch that has custom development to fix a lot of these constraining design decisions. When I make edits, I commit all of the changed files (some are in custom/ and some aren't unfortunately) to my own branch and then create the upgrade file as noted in my last post. That has worked well in an otherwise stateless environment to at least make sure the application is consistent between servers. The user preference thing is obviously still broken, but the app works.

**Comment by yurikuzn** [comment]
@arkitechtura any customization made via Administration tools are stored in custom folder. There are metadata files and generated classes. Your customization should be migrated just with copying of custom folder. You also will need to run Rebuild.

**Comment by bandtank** [comment]
Extensions should go with the build if you run a proper deployment pipeline assuming you install them locally as well. The only thing that won't move is user preference files.

**Comment by tannakartikey** [comment]
@bandtank I don't know fully about how the app works yet. So there are no plans yet for 'uploads' directory.

It will take some time going through the code and play with a few installations. 

The information shared on this thread is going to help a lot by @yurikuzn and @bandtank

**Comment by alasdaircr** [comment]
I have cobbled together some mods to the grunt config and shell scripts in order to manage a heavily patched Espo, with 'production' + 'staging' versions

Dealing with major upgrades requires examining the released ZIP files and reading the pre/postUpgrade callbacks to check for any fixes.

It's not pretty, I normally upgrade a few weeks after each major upgrade. I regularly have to refactor my patches against core as changes happen. This is just par for the course but the ideal scenario would be no patches to core and manage all my modifications via Extensions. Some things are not possible in Extensions however.

**Comment by bandtank** [comment]
@yurikuzn Where can I find an example of this? "If there were some significant changes that can't be processed just by files replacement we write afterUpgrade or beforeUpgrade scripts manually and include them into upgrade package."

I regularly merge master into my copy of the repository, but I don't know if I'm missing something by doing things that way.

**Comment by alasdaircr** [comment]
@bandtank see my comment above "Dealing with major upgrades requires examining the released ZIP files and reading the pre/postUpgrade callbacks to check for any fixes."

Just replace pre/post with before/after

**Comment by bandtank** [comment]
I read your comment, but I don't know what that means or where to find an example of it. I don't understand why scripts would be necessary before or after an upgrade because I don't know what they're doing yet.

**Comment by alasdaircr** [comment]
Download an update file then from sourceforge and examine it.

https://sourceforge.net/projects/espocrm/files/Upgrades/

As to why they use sourceforge rather than github I have no idea.

**Comment by alasdaircr** [comment]
That's probably where the confusion arises. The zip files available on github represent 'new install' packages so do not have any upgrade code.

**Comment by bandtank** [comment]
I see. Thanks. At some point, it would be really nice if the documentation, download files, etc. all existed in a single place. I had no idea sourceforge was even part of the equation until just now.

**Comment by yurikuzn** [comment]
Link to upgrades is avaialble at Administration > Upgrade
https://www.espocrm.com/download/upgrades/

**Comment by bandtank** [comment]
@alasdaircr After looking at the files, I'm not sure if I need to run these scripts or not. If I'm merging master into my repository, is that going to achieve the same end result as running the upgrade packages? I realize this isn't supported so I'm not asking for anything to be changed. I'm just trying to figure out how you incorporate changes into your repository and how you do releases.

**Comment by alasdaircr** [comment]
I've found you do need to keep an eye on the scripts and look for changes. Most of the before/after scripts are the same in each upgrade, they add default reports in the Advanced pack or set configuration settings. But now and again something is in there, e.g. fixing a problem with data in a table which you should read, figure out if it's relevant and perform the step manually yourself.

Unfortunately there's no other way to manage this as far as I know.

**Comment by alasdaircr** [comment]
Long term, one way to handle this would be to hook your core changes into the existing upgrade system. Perhaps your changes could be a final 'upgrade file' that applies your changes on top of the latest version. You could even tweak the version number by appending ``-custom-gitsha`` or similar.

So rather than rebase your changes onto master, youd 'rebase' your changes into an upgrade file. With each upgrade released from Espo you'd have to generate another ``espocrm-upgrade-xxx-to-custom-gitsha`` package?

**Comment by yurikuzn** [comment]
Since now it is possible to build upgrades packages on forked repositories.

In linux terminal:

```
grunt
node diff --all --vendor
```

It will include vendor files (only changed) and scripts.

Packages will be available in `build` directory.
