### ISSUE TITLE
Funtion request: Emoticons in Stream

### ISSUE THREAD

**Issue by buzzard10** [espocrm/espocrm#781]
I think you shoud consider emoticons in stream :)

**Comment by bandtank** [comment]
Please don’t. Emoticons are incredibly unprofessional.

**Comment by rodrigoscoelho** [comment]
This is subjective. I think it would be better to let people choice if they
would use or not. Don't having it as an option because some think it is
unprofessional is not a good way.

IMHO.

_______________________________________




*Rodrigo Sírio Coelho*

*Diretor*

rodrigocoelho@fratar.com.br

Tel: +55 31 4063.6787 - Ramal 234

Cel: +55 31 98489.0807

2018-01-29 11:13 GMT-02:00 Anthony Andriano <notifications@github.com>:

**Comment by bandtank** [comment]
It's really not subjective. Professional people convey their points without needing to dress up text with smiley faces and poop emojis. Go chat on tinder if you can't articulate your points in a professional manner without a smiley face.

Regardless, it's definitely a waste of time. I really hope they don't waste resources implementing this over the many other features that are actually useful. If for some reason they're smoking crack and think this should be done, please for the love of god give us a checkbox to disable it.

**Comment by yurikuzn** [comment]
If adding emojis support took only 1-2 hours of work I think would do it.  An ability to turn on/off emojis globally for an entire system is a necessity. Maybe off by default.

At this moment we have a big todo list to be done for core functionalities. So, maybe in future.

**Comment by yurikuzn** [comment]
I think reactions to the posts, like github has, are more reasonable. In-text emojis I wouldn't like to have.

**Comment by emillod** [comment]
@bandtank thanks for Your reply. I think You're right - Espo Devs have much more important functions to implement in Espo, but I don't know why You're so irritated about my proposal. 
For example Slack has emoticons - do You know how many companies using slack? They're all unprofessional because They have emoticons? 👍 
@rodrigoscoelho  thanks for reply 🥇 
@yurikuzn - it's a step forward, thanks :)
