### ISSUE TITLE
Feature: Task multi user assignable

### ISSUE THREAD

**Issue by ayman-alkom** [espocrm/espocrm#79]
Can task be multiple user assigned ?

**Comment by yurikuzn** [comment]
After 4.0. or 4.1 it will be easy to switch to multiple assigned users. But it will still require a minor customization.

**Comment by bastians** [comment]
Cool, also for other objects than tasks? E.x. contacts or organizations?

**Comment by ayman-alkom** [comment]
Thanks a lot for your job @yurikuzn 
we are waiting

**Comment by ayman-alkom** [comment]
Milestone 4.0 here?

**Comment by yurikuzn** [comment]
Not sure yet, but it will be much easier to switch to multi assigned users since 4.0.

**Comment by ayman-alkom** [comment]
does we have a chance now for this

**Comment by yurikuzn** [comment]
You can try to create linkMultiple field assignedUsers and use instead of assignedUser on side panel. But I can't give garantees.

**Comment by bandtank** [comment]
Was this ever finished/fixed/released? I need to assign tasks to multiple users who will see the task listed in the My Tasks dashlet using the 'only my' filter.

**Comment by yurikuzn** [comment]
You need to create `assignedUsers` link many-to-many with Link Multiple field. And then add this field to side panel instead of `assignedUser` (see https://github.com/espocrm/espocrm/blob/master/application/Espo/Modules/Crm/Resources/metadata/clientDefs/Contact.json#L11 how to do it.). But no garantees whether everything will work fine. There were people who managed this to work.
