### ISSUE TITLE
Sorting entries needs enhancement

### ISSUE THREAD

**Issue by karthik-uc** [espocrm/espocrm#795]
## Problem

Right now, we can sort the column in Leads/Contacts/Any Other by one column. It would be really nice if we can sort entries by one or more columns.

For example, I would want to sort the leads by created time(desc) and status. The reason is I want first approach people who came in as leads the latest and status is still new. The second sorting item need not be always status, it can be something else also like custom field. 

- Basically I want to find new entries sorted by created date descending. 
- (When lead was not available for the first follow up) Second time follow up entries sorted by created date descending.
- (When lead was not available for the second follow up) Third time follow up entries sorted by created date descending. 
And so on...

Ability to Group the leads are also useful.

Example mysql query

```mysql
select * from `espocrm`.`lead` group by `espocrm`.`lead`.`status` order by `espocrm`.`lead`.`createdTime` desc, `espocrm`.`lead`.`modifiedTime` asc
```

**Comment by bandtank** [comment]
I find myself needing this pretty frequently. It would be a huge help.

**Comment by imbhat** [comment]
@PanuWeb 

I understand that filter are very useful for doing such things. However, I am not the one using the application. The one using the application is either a sales agents who are not good with tech. Adding 10 filters will make too many filters and becomes unmanageable for a dev as well as sales agents. And the fields and their values vary from time to time. Most of time is spent building filters then.

If it was one filter, I can add it. But they want to see the data in 10 different ways. Reports doesn't help because reports are used to generate analytics. Sales agents look to tackle leads and communicate with the leads through Espo. They don't need how many leads came in with certain type of data. What they look for is, hey, 
- if 10 people came through google Ad campaign, this(something) is how I am going to approach them. 
- If 50 people came through email marketing, this(another route) is how I am going to approach them.

**Comment by bandtank** [comment]
You can use reports to solve the problem you explained. Reports do a lot more than generate analytics. They can be used as search filters in entity lists, dashlets, triggers for workflows, triggers for processes, triggers for emails, and many other things.

I don’t undrrstsnd how managing filters is complicated. My users are able to manage many reports with many filters and they are not savvy when it comes to computers.

For example, I created three reports to show the status of projects. Each report has between 10 and 15 filters. My users add dashlets based on these reports to customize their workflows, which has worked extremely well. I also bass processes on the results of the three reports I mentioned to trigger user tasks. One of the reports also syncs with a target list to send mass emails.

It takes about 30 seconds to create a new report with customized filters. It takes even less time to update an existing report. I don’t understand how reports are too time consuming to work in your situation.

**Comment by PanuWeb** [comment]
@imbhat I am not against your proposal, but in the examples that you show us, applying only one filter is enough. For the two examples with choosing campaign filter and selecting the desired campaign you have the results.

In any case the answer of @bandtank is also valid.

Maybe I can not imagine such a complicated situation (I am a developer and I use it for myself and a colleague).

Anyway, if the option to sort by two or more columns is implemented, it would be welcome.

Regards!

**Comment by imbhat** [comment]
@PanuWeb @bandtank 

I understand that reports can be useful. However, reports are meant to generate reports.

If I want to work on my leads, why would I go and look at/generate reports? The ordering options should be on lead because I am working on leads.

- Filters doesn't help because I want ordering (asc, desc) of multiple column, not filtering.
- Too many filters are difficult to manage.

**Comment by bandtank** [comment]
You don’t appear to actually understand what reports are capable of doing. They do a lot more than, as you said, generate reports. That’s is the most obvious and simple use-case for an report, yes, but the functionality extends far beyond that.

Your original question can be solved very easily by creating a custom report via code. There’s nothing stopping you from running your sql query in a custom report class.

Managing filters is not complex. My computer illiterate users can handle filters without any trouble, so I don’t see any reason to continue debating this point. If you think filters are too complex, I’m not sure why you are using a CRM tool because they are practically the essence of data management.

Sorting by multiple columns in a report is literally the answer to the question you asked. You seem to want to use that functionality in List views, which would make sense except for grouping. List views are not meant to do data mining and analytics, which is what you are doing when you need to group and sort data in a complex way. This is also why reports are the right place to look at Leads in your case; reports are the basis for preset filters, dashlets, workflows, processes, emails, target lists, and more advanced things if you are capable of writing custom classes.

**Comment by PanuWeb** [comment]
> List views are not meant to do data mining and analytics, which is what you are doing when you need to group and sort data in a complex way. This is also why reports are the right place to look at Leads in your case

That is the point that I could not find.
